travis:
  secure:
    BINSTAR_TOKEN: nUrNFDpqUfl/PyvIUohTnvPakl6mad1exXMBvnM6AeWgEWh7n/pP3cQ5xoC5ob8NDOYMY/emKTtNOV4zGeJrJUmGivOEZ/9AOd4rg7DuvdDUNAtzd09MkH95dem+Q/rLXZuppo8Lh61hdufNtR0U2zdeZvoQmcYp+exLNalbPsp0OJOthiKkvkrAGk1Xg/Et2Qxb4ZiGDSEYBsx6fbyXBBfje5O91gkDNEQXKYXNzQtrnTx2zruOGK/SiMf7hZNTwUGerkBxag+x8kl0fq3Yv8WJRcQUNRmoQ6jsYjXZb7fixDV33OCf4C0/ZPzstLynG7D6V2Zw3EhlBWd8HB6mY++gdM4gGLX1GbQfzL/me+eG+Wc0Ey+SqV7dx5Ks5wvQjbYMXpROKz4Y9xpm38AisgQXU46n3BApz9DE3jEkfux4onCchi2cWl9gH2MnHTGxMsTrlqLDyCp7y5XPgwSdqqKoRcsPUJi4/bRkufT+8gUbLhVXlmjTukmr1JJuXXEa8lxAL4gkOYEZfG6CjmYQA0MQVMQkveTuGFT62e9qLZkb7hLwWqPBPjLDZV27Rqbqtgv1M5wBGqrA8LzQ8Zel2gyY/rEJ+cDTDg7xhk2+BQnJAgQPUBvarpclSHCDWr9M+DrSjuw8gYVYHiWvYmi2V5TWqBm/rPl03mUfw7FL6mM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
