travis:
  secure:
    BINSTAR_TOKEN: PktSG7Jj49QdjQJufLP+6aK3snLLtTci8ZphdBDmQTicx639IvhnmN+8tMfWdlPNtskBVTFASG0Ama3a39DFhGT49dEgIkrb+Dm9HuJwUxcI4xPrsrqEMlJ+U135CHqRlDIVnI8DgX5ZnawmYiDXW4YVsnIzfb7HlVc0z2AXSZD6PzM6Dc3T+9v/3gPt1OU10qbKJs/sXXvvT9RrfaAC87KoPHtdcvBd5y9oB8cGbMhBXMOimwLfOAPwnhZ8LxUWnU5RMhLGh90aM+ecQQB9ARyxGzXSJNfZ1eMv3gUx8V1P3upjeGbu1TE93wEY5JKoT5o85AJ7A+K/rYmh5/5udqm8vqFcqzw5gqoVzMM7e48zfJOHZlMsAGkwRw5bGvYNjzt3D3h4HPvA5ZXOw3tyxEoYJ+tlA6alpbYQvOw1467rbWwX20f+dwhQq4vB9P19gPW0Ca2RB5ilKv3GSYEi+Z1N++GgQK68/pJKlSWUyxL7xhUnNgUy5Un+NrXwz9mqhrCWq+m4XaVdLL3wiVkcupbdUGhwNx4VaxEjymRtxyREpTPVI0mqWuVsZpQtISbxM/v/rI2pLkekg5AwjTTBjWLi2tpgxFobNzpjv+lY1zGUZiqmpNRUXzFme8OfCRr/JLddGJwvRCdJ4zTUtxOmm1QrVd1wV5ekJPwBFnmFC44=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
