travis:
  secure:
    BINSTAR_TOKEN: cIeEvMqgmY/7nRSBuJ8+blREipl4APo2gcziCxTSo3OB78tbnbgN47/ge7nq3Uxw7me4Qry5TurgMB1uSezCU7jW5EJm4m6mCa5Rv+K09XdDYpI1it8Jen3thbBwlm5swnk0qzCRSg2iHwfZGaRS2r691whMAm4P60DDdMrrVsq1galnhgpIbGUpSliSOHSWsyFFipEz3r6/6FAeTvKBMVVnOMzCn8tdeblN3zi7eZSyNjr7pl2ggptt5RoqHSpj4rhj2KTWZZFjYw3kmXSFmCc3rgoUkyazwDGJ99FGUDdLOVaDXNjDf64m21RkEjYao+V5uoLl4YvXSiv1Z08qYObW8+shXWTG5PSx59Pwgs/Szy4/uZEuRu/NQ1gwv8gWOVlEBuaoV7GrDd25t0PmNh/+yPzyk1wdTZKZfmw4C6GzYonjwhrD6VPb62JuPWPG6E30qguy+Ssmz2d97CUuSX8SnDqdXGoEr1cnVidYUvz1inypk48m29Oo9yaJ4ZWIFjY6R2PskxC80yPkIkNDPy6M/MEBbXQfoUhdHEOo761MbE+z4uJHPqWw6wDJmoliMknnx/MfMHw2WdpMYvAw91yu9/Od38gDALZZLp6uUCXiajXQoXE5NMw8mOdxg89qhZ9rpf2qRWnqjiG6y31AZBX5sKwYuHIIMnZGEU2fAJE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
