travis:
  secure:
    BINSTAR_TOKEN: mWbPAoxaQeHVxjFQfwIvqZZrnByTHqL2sJesURRMQHrvK9ee28Pt8ZHO/G9sGUfYw2WQEUeH5+rd3k2kbyO7UHoUcb6316NLid93peX71zYFrRUAAmqGVv+8tv84dvAPGfj3K/FsF2XaAzBbK9dTTEtHRxuA25czbZUj8HTYf5rKaV1GT9kACa2Xp6t+Demg6exMkD1NIrhKiJFZ76wwPraUp1tb3+Q4CWldTUrcNzYVpnSDhqBo3PapDZLey1PtN1XIFe0Trpx3iF38FVah5Zm7K9cl46+Z0PyynL5bw3/c4Z7NwxwEev/khE9oQ0pFjcc4TpQhTe0sBVmBI/uJisSA+ARgzjZQcTUF4u1yEmrV+KVbq37f8liuQjB8Y8E+0TlBPzJ/1/h2JZ8Z+/hsZYc3Hm/XeLmBmOb8IsccM0dhBAWMwJzSkBhe0SptuZrh2JZ5o4y3Z86sedY+h0CFISdfwXae/CpysNrLHzyU5cR9aPGnCHHNhAgSqSd/DdoYw/kaSyACKWtR/n6qSA/zoHWNu6LXwLUwK63vQ3yQoKdyIaosYtc2epg+TG5uLX0V8dhtriA6cKbA4s6/OZJnt07w4p8G0IJ5oMUZbnopV3WPTtdqYs0IH4u39BzGrazo2s1qz4/udLxsLCxkbYjr2NB91MVHg2rRaq9sRmcS1dQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
